# World Energy Consumption

In [1]:
import pandas as pd
import numpy as np

from bokeh.io import output_notebook
from bokeh.plotting import figure, show

In [2]:
#@title Loading Data
LoadCsv = 'https://raw.githubusercontent.com/AshrafulPatHan/notebook/main/World%20Energy%20Consumption/World%20Energy%20Consumption.csv'
data = pd.read_csv(LoadCsv)
data.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

In [3]:
output_notebook()

In [4]:
#@title year to biofuel_electricity

p = figure(title="year vs biofuel_electricity",width=400, height=400)

p.scatter(data['year'], data['biofuel_electricity'], size=20, color="navy", alpha=0.5)

p.xaxis.axis_label = "year"
p.yaxis.axis_label = "biofuel_electricity"

show(p)

## Sort Country

In [32]:
High_Population = data[(data['year'] == 2022) & (data['population'] > 160000000)]
High_Population

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
267,Africa,2022,NaN,1.426737e+09,NaN,1.068,0.012,0.786,1.122,NaN,...,2.037,0.842,4.888,2.686,62.294,16.747,23.894,43.662,2.676,1.107
1271,Asia,2022,NaN,4.721383e+09,NaN,8.683,17.534,46.484,219.470,NaN,...,4.600,2.152,15.420,308.514,2365.340,192.159,907.256,500.985,5.595,2.618
2125,Bangladesh,2022,BGD,1.711864e+08,NaN,NaN,NaN,NaN,NaN,0.175,...,0.763,0.344,0.000,-0.000,0.013,0.058,0.010,0.077,0.012,0.003
2975,Brazil,2022,BRA,2.153135e+08,NaN,-0.631,-1.535,1123.715,241.951,266.681,...,3.889,2.109,12.929,23.675,212.824,371.551,80.000,988.440,11.750,5.714
4405,China,2022,CHN,1.425887e+09,NaN,-1.205,-0.340,19.549,27.874,120.718,...,4.756,2.519,16.300,272.433,1988.450,561.419,800.520,1394.535,9.057,4.491
6684,Europe,2022,NaN,7.448070e+08,NaN,9.038,19.881,322.048,239.864,NaN,...,4.878,2.130,11.023,131.071,1365.527,703.223,523.766,1833.398,10.955,4.784
7005,European Union (27),2022,NaN,4.473159e+08,NaN,7.552,14.650,466.433,208.643,NaN,...,7.370,3.343,8.836,85.312,1096.260,940.017,420.484,2450.750,14.953,6.783
8758,High-income countries,2022,NaN,1.224122e+09,NaN,5.548,37.138,577.188,706.549,NaN,...,5.485,2.438,13.005,306.178,2737.438,857.741,1049.979,2236.247,8.910,3.960
9288,India,2022,IND,1.417173e+09,NaN,14.897,4.693,25.542,36.198,25.755,...,5.178,2.451,2.865,4.437,182.617,49.429,70.050,128.860,3.811,1.804
9411,Indonesia,2022,IDN,2.755013e+08,NaN,12.307,10.590,350.763,96.636,74.918,...,0.132,0.029,-18.535,-0.215,0.928,1.307,0.360,3.369,0.108,0.034
11045,Low-income countries,2022,NaN,7.175874e+08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11168,Lower-middle-income countries,2022,NaN,3.447031e+09,NaN,13.157,16.312,40.698,140.288,NaN,...,3.776,1.583,6.681,15.108,255.201,28.397,97.886,74.035,2.652,1.112
13707,Nigeria,2022,NGA,2.185412e+08,NaN,NaN,NaN,NaN,NaN,0.092,...,0.156,NaN,NaN,NaN,NaN,0.000,0.000,NaN,0.000,NaN
14072,North America,2022,NaN,6.003237e+08,NaN,3.829,17.094,772.182,463.559,NaN,...,4.139,1.812,13.433,149.948,1301.692,831.686,499.281,2168.316,8.855,3.876
15775,Pakistan,2022,PAK,2.358249e+08,NaN,NaN,NaN,NaN,NaN,7.166,...,0.940,0.232,35.511,3.145,12.126,17.471,4.120,51.421,2.707,1.212
18056,South America,2022,NaN,4.368167e+08,NaN,0.629,1.707,625.538,273.246,NaN,...,3.970,1.772,12.552,31.750,293.241,257.491,112.476,671.313,8.948,3.995
20710,United States,2022,USA,3.382899e+08,NaN,4.335,18.026,1282.526,433.866,158.030,...,4.754,2.018,14.970,145.448,1145.063,1285.318,434.810,3384.858,10.119,4.298
20949,Upper-middle-income countries,2022,NaN,2.555056e+09,NaN,0.992,3.392,135.210,345.468,NaN,...,4.060,1.930,15.228,315.344,2444.863,367.021,937.759,956.873,7.349,3.494
21631,World,2022,NaN,7.975105e+09,NaN,4.929,56.335,150.369,1199.207,84.961,...,4.519,2.055,13.523,636.006,5487.600,268.238,2139.230,688.091,7.499,3.271

In [35]:
# 3. Sort the results by population from highest to lowest
sorted_High_Population = High_Population.sort_values(by="population", ascending=False)
sorted_High_Population

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
21631,World,2022,NaN,7.975105e+09,NaN,4.929,56.335,150.369,1199.207,84.961,...,4.519,2.055,13.523,636.006,5487.600,268.238,2139.230,688.091,7.499,3.271
1271,Asia,2022,NaN,4.721383e+09,NaN,8.683,17.534,46.484,219.470,NaN,...,4.600,2.152,15.420,308.514,2365.340,192.159,907.256,500.985,5.595,2.618
11168,Lower-middle-income countries,2022,NaN,3.447031e+09,NaN,13.157,16.312,40.698,140.288,NaN,...,3.776,1.583,6.681,15.108,255.201,28.397,97.886,74.035,2.652,1.112
20949,Upper-middle-income countries,2022,NaN,2.555056e+09,NaN,0.992,3.392,135.210,345.468,NaN,...,4.060,1.930,15.228,315.344,2444.863,367.021,937.759,956.873,7.349,3.494
267,Africa,2022,NaN,1.426737e+09,NaN,1.068,0.012,0.786,1.122,NaN,...,2.037,0.842,4.888,2.686,62.294,16.747,23.894,43.662,2.676,1.107
4405,China,2022,CHN,1.425887e+09,NaN,-1.205,-0.340,19.549,27.874,120.718,...,4.756,2.519,16.300,272.433,1988.450,561.419,800.520,1394.535,9.057,4.491
9288,India,2022,IND,1.417173e+09,NaN,14.897,4.693,25.542,36.198,25.755,...,5.178,2.451,2.865,4.437,182.617,49.429,70.050,128.860,3.811,1.804
8758,High-income countries,2022,NaN,1.224122e+09,NaN,5.548,37.138,577.188,706.549,NaN,...,5.485,2.438,13.005,306.178,2737.438,857.741,1049.979,2236.247,8.910,3.960
6684,Europe,2022,NaN,7.448070e+08,NaN,9.038,19.881,322.048,239.864,NaN,...,4.878,2.130,11.023,131.071,1365.527,703.223,523.766,1833.398,10.955,4.784
11045,Low-income countries,2022,NaN,7.175874e+08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14072,North America,2022,NaN,6.003237e+08,NaN,3.829,17.094,772.182,463.559,NaN,...,4.139,1.812,13.433,149.948,1301.692,831.686,499.281,2168.316,8.855,3.876
7005,European Union (27),2022,NaN,4.473159e+08,NaN,7.552,14.650,466.433,208.643,NaN,...,7.370,3.343,8.836,85.312,1096.260,940.017,420.484,2450.750,14.953,6.783
18056,South America,2022,NaN,4.368167e+08,NaN,0.629,1.707,625.538,273.246,NaN,...,3.970,1.772,12.552,31.750,293.241,257.491,112.476,671.313,8.948,3.995
20710,United States,2022,USA,3.382899e+08,NaN,4.335,18.026,1282.526,433.866,158.030,...,4.754,2.018,14.970,145.448,1145.063,1285.318,434.810,3384.858,10.119,4.298
9411,Indonesia,2022,IDN,2.755013e+08,NaN,12.307,10.590,350.763,96.636,74.918,...,0.132,0.029,-18.535,-0.215,0.928,1.307,0.360,3.369,0.108,0.034
15775,Pakistan,2022,PAK,2.358249e+08,NaN,NaN,NaN,NaN,NaN,7.166,...,0.940,0.232,35.511,3.145,12.126,17.471,4.120,51.421,2.707,1.212
13707,Nigeria,2022,NGA,2.185412e+08,NaN,NaN,NaN,NaN,NaN,0.092,...,0.156,NaN,NaN,NaN,NaN,0.000,0.000,NaN,0.000,NaN
2975,Brazil,2022,BRA,2.153135e+08,NaN,-0.631,-1.535,1123.715,241.951,266.681,...,3.889,2.109,12.929,23.675,212.824,371.551,80.000,988.440,11.750,5.714
2125,Bangladesh,2022,BGD,1.711864e+08,NaN,NaN,NaN,NaN,NaN,0.175,...,0.763,0.344,0.000,-0.000,0.013,0.058,0.010,0.077,0.012,0.003

Warning: Total number of columns (129) exceeds max_columns (20) limiting to first (20) columns.

## Contry Details

In [8]:
#@title Add Country Name
CountryName = 'Bangladesh' #@param {type:"string"}
country = data[data['country'] == CountryName].copy()
country

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
2003,Bangladesh,1900,BGD,26849595.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004,Bangladesh,1901,BGD,26958449.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005,Bangladesh,1902,BGD,27067609.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006,Bangladesh,1903,BGD,27177073.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007,Bangladesh,1904,BGD,27286841.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2121,Bangladesh,2018,BGD,163683952.0,6.865218e+11,NaN,NaN,NaN,NaN,0.183,...,0.379,0.169,0.000,-0.0,0.013,0.061,0.01,0.082,0.014,0.003
2122,Bangladesh,2019,BGD,165516224.0,NaN,NaN,NaN,NaN,NaN,0.181,...,0.415,0.179,0.000,-0.0,0.013,0.060,0.01,0.081,0.013,0.003
2123,Bangladesh,2020,BGD,167420944.0,NaN,NaN,NaN,NaN,NaN,0.179,...,0.515,0.224,0.274,-0.0,0.013,0.060,0.01,0.080,0.013,0.003
2124,Bangladesh,2021,BGD,169356240.0,NaN,NaN,NaN,NaN,NaN,0.177,...,0.583,0.321,-0.273,-0.0,0.013,0.059,0.01,0.079,0.012,0.003
2125,Bangladesh,2022,BGD,171186368.0,NaN,NaN,NaN,NaN,NaN,0.175,...,0.763,0.344,0.000,-0.0,0.013,0.058,0.01,0.077,0.012,0.003

Warning: Total number of columns (129) exceeds max_columns (20) limiting to first (20) columns.

In [26]:
country[['year', 'population']]

      year   population
2003  1900   26849595.0
2004  1901   26958449.0
2005  1902   27067609.0
2006  1903   27177073.0
2007  1904   27286841.0
...    ...          ...
2121  2018  163683952.0
2122  2019  165516224.0
2123  2020  167420944.0
2124  2021  169356240.0
2125  2022  171186368.0

[123 rows x 2 columns]

In [30]:
display(country['gdp'])

2003             NaN
2004             NaN
2005             NaN
2006             NaN
2007             NaN
            ...
2121    6.865218e+11
2122             NaN
2123             NaN
2124             NaN
2125             NaN
Name: gdp, Length: 123, dtype: float64